nodes:
  web1:
    ip: 192.168.188.50
    role: web-server
    framework: node
    tls: yes
    certificates:
    - wildcard-tf-demos-co-uk
    - wildcard-infratechy-co-uk
    sites:
    - app1
    - app2
  lb1:
    ip: 192.168.188.51
    role: load-balancer
    framework: none
    tls: yes
    certificates:
    - wildcard-tf-demos-co-uk
  web2:
    ip: 192.168.188.52
    role: web-server
    framework: node
    tls: no
  web3:
    ip: 192.168.188.53
    role: web-server
    framework: node
    tls: no
